#!/bin/sh
#set -x
# PROVIDE: multihop
# REQUIRE: NETWORKING SERVERS
# BEFORE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="multihop"
rcvar=multihop_enable

command="/usr/local/opnsense/scripts/OPNsense/Multihop/multihop.sh"
pidfile="/var/run/${name}.pid"

start_cmd="${command} start"
status_cmd="${command} status"


load_rc_config $name

: ${multihop_enable="NO"}

run_rc_command "$1"
